include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - '**/*.g.dart'

analyze:
  rules:
    prefer_const_constructors: true
    prefer_conditional_assignment: true
    prefer_const_declarations: true
    sort_constructors_first: true